name: Experimental Pull Request Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  integration-check:
    name: Integration Check
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Set Commit Status
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.event.pull_request.head.repo.full_name }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${REPO}/statuses/${SHA}" \
            -f state="pending" \
            -f context="experimental-pr-check"

      - name: Check Review Decision
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api graphql \
            -f owner="$OWNER" \
            -f repo="$REPO" \
            -F number="$NUMBER" \
            -f query='
              query( $owner: String!, $repo: String!, $number: Int! )
              {
                repository( owner: $owner, name: $repo )
                {
                  pullRequest( number: $number )
                  {
                    reviewDecision
                  }
                }
              }'
          echo .
          echo "Repository Owner: ${{ github.event.repository.owner.login }}"
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request Author Association: ${{ github.event.pull_request.author_association }}"
