name: Integration Check

on:
  pull_request:
    types:
      - labeled

jobs:
  integration:
    name: Integration
    if: github.event.label.name == 'integration-ready'
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write
    steps:
      - name: Log Ref Details
        run: |
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
          echo
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_protected: ${{ github.ref_protected }}"

      - name: Remove Integration Labels
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-ready" \
            || echo "Failed to remove label: integration-ready"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-running" \
            || echo "Failed to remove label: integration-running"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-success" \
            || echo "Failed to remove label: integration-success"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-failure" \
            || echo "Failed to remove label: integration-failure"

      - name: Check Approval
        id: approval
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          NUMBER: ${{ github.event.pull_request.number }}
        run: |
          REVIEW_DECISION="$(
            gh api graphql \
              -f owner="$OWNER" \
              -f repo="$REPO" \
              -F number="$NUMBER" \
              -f query='
                query( $owner: String!, $repo: String!, $number: Int! )
                {
                  repository( owner: $owner, name: $repo )
                  {
                    pullRequest( number: $number )
                    {
                      reviewDecision
                    }
                  }
                }' \
              -q ".data.repository.pullRequest.reviewDecision"
            )"

          echo "Repository Owner: ${{ github.event.repository.owner.login }}"
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request Author Association: ${{ github.event.pull_request.author_association }}"
          echo "Review Decision: $REVIEW_DECISION"

          if [[ "$REVIEW_DECISION" == "APPROVED" || "${{ github.event.pull_request.author_association }}" == "OWNER" ]]; then
            echo "Approved: true"
            echo "approved=true" >> "$GITHUB_OUTPUT"
          else
            echo "Approved: false"
            echo "approved=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Integration Success
        if: steps.approval.outputs.approved == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
          COMMIT_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          PR_REPO_OWNER: ${{ github.event.repository.owner.login }}
          PR_REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${COMMIT_REPO}/statuses/${COMMIT_SHA}" \
            -f state="success" \
            -f context="integration-check"

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${PR_REPO_OWNER}/${PR_REPO_NAME}/issues/${PR_NUMBER}/labels" \
            -f labels[]="integration-success"
