name: Integration Reset

on:
  push:

jobs:
  reset-integration-status:
    name: Reset Integration Status
    runs-on: ubuntu-latest

    steps:
      - name: Logging
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          REF: ${{ github.ref_name }}
        run: |
          echo "Owner: $OWNER"
          echo "Repo: $REPO"
          echo "Ref: $REF"
          RESPONSE="$(
            gh api graphql \
              -f owner="$OWNER" \
              -f repo="$REPO" \
              -f ref="$REF" \
              -f query='
                query( $owner: String!, $repo: String!, $ref: String! )
                {
                  repository( owner: $owner, name: $repo )
                  {
                    pullRequests( baseRefName: $ref, first: 20 )
                    {
                      nodes
                      {
                        number
                        title
                        state
                        statusCheckRollup
                        {
                          state
                        }
                        headRefName
                        headRefOid
                      }
                    }
                  }
                }' )"
          echo "$RESPONSE" | jq -r '
            .data.repository.pullRequests.nodes[]
            | [
              .number,
              .title,
              .state,
              (.statusCheckRollup.state // "NONE"),
              .headRefName,
              .headRefOid ]
            | @tsv
          ' | while IFS=$'\t' read -r NUMBER TITLE STATE STATUS_CHECK HEAD_REF_NAME HEAD_REF_OID
          do
            echo .
            echo "Number: $NUMBER"
            echo "Title: $TITLE"
            echo "State: $STATE"
            echo "Status Check: $STATUS_CHECK"
            echo "Head Ref Name: $HEAD_REF_NAME"
            echo "Head Ref OID: $HEAD_REF_OID"
          done
