name: Integration Reset

on:
  push:

jobs:
  reset-integration-status:
    name: Reset Integration Status
    runs-on: ubuntu-latest

    steps:
      - name: Logging
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          REF: ${{ github.ref_name }}
        run: |
          echo "Owner: $OWNER"
          echo "Repo: $REPO"
          echo "Ref: $REF"
          RESPONSE="$(
            gh api graphql \
              -f owner="$OWNER" \
              -f repo="$REPO" \
              -f ref="$REF" \
              -f query='
                query( $owner: String!, $repo: String!, $ref: String! )
                {
                  repository( owner: $owner, name: $repo )
                  {
                    pullRequests( baseRefName: $ref, first: 20 )
                    {
                      nodes
                      {
                        number
                        title
                        state
                        statusCheckRollup
                        {
                          state
                        }
                        headRefName
                        headRefOid
                      }
                    }
                  }
                }' )"
          echo "$RESPONSE" | jq -r '
            .data.repository.pullRequests.nodes[]
            | "
          Number: \(.number)
          Title: \(.title)
          State: \(.state)
          Status Check: \(.statusCheckRollup.state // "NONE")
          Head Ref Name: \(.headRefName)
          Head Ref OID: \(.headRefOid)"'
