name: Integration Check

on:
  pull_request:
    types:
      - labeled

jobs:
  integration:
    name: Integration
    if: github.event.label.name == 'integration-ready'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Logging
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api graphql \
            -f owner="$OWNER" \
            -f repo="$REPO" \
            -F number="$NUMBER" \
            -f query='
              query( $owner: String!, $repo: String!, $number: Int! )
              {
                repository( owner: $owner, name: $repo )
                {
                  pullRequest( number: $number )
                  {
                    reviewDecision
                  }
                }
              }'
          echo .
          echo "Repository Owner: ${{ github.event.repository.owner.login }}"
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request Author Association: ${{ github.event.pull_request.author_association }}"

      - name: Remove Integration Labels
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-ready" \
            || echo "Failed to remove label: integration-ready"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-running" \
            || echo "Failed to remove label: integration-running"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-success" \
            || echo "Failed to remove label: integration-success"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${OWNER}/${REPO}/issues/${NUMBER}/labels/integration-failure" \
            || echo "Failed to remove label: integration-failure"
